name: "Refresh SSL Cert From Asus DDNS Router"
version: "0.0.1"
slug: "refresher_ssl_cert_from_asus_ddns_router"
description: "An Add-on that help refresh the SSL certificate under the /SSL folder from Asus Router DDNS"
arch:
  - amd64
map:
  - ssl