name: "Refresh SSL Cert From Asus DDNS Router"
version: "0.0.1"
slug: "refresher_ssl_cert_from_asus_ddns_router"
description: "An Add-on that help refresh the SSL certificate under the /SSL folder from Asus Router DDNS"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - ssl:rw
options:
  sslFromAsusRouter:
    routerUser: null
    routerIp: null
    routerSshHostKey: null
    keyFilePathOnRouter: null
    certFilePathOnRouter: null
schema:
  sslFromAsusRouter:
    routerUser: str
    routerIp: str
    routerSshHostKey: str
    keyFilePathOnRouter: str
    certFilePathOnRouter: str