name: nightly-build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    name: Deploy nightly-build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Get Add-on Release
        uses: KJ002/read-yaml@v1.4
        id: addonVersion
        with:
          file: 'config.yaml'
          key-path: '["version"]'

      - name: Deploy Nightly Build
        uses: home-assistant/builder@2022.01.0
        with:
          args: |
            --docker-hub ghcr.io \
            --docker-user ${{ github.actor }} \
            --docker-password ${{ secrets.GITHUB_TOKEN }} \
            --all \
            --target . \
            --addon \
            --base "${{ steps.addonVersion.outputs.data }}-SNAPSHOT"