name: test-builds
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        if: env.BUILD_ARGS == '--docker-hub-check'
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_HUB_REGISTRY_READER_TOKEN }}

      - name: Checkout the repository
        uses: actions/checkout@v2
        
      - name: Test build
        uses: home-assistant/builder@2022.01.0
        with:
          args: |
            --test \
            --all \
            --target .